# Generated by Django 4.2.3 on 2023-07-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoty_post_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
