# Generated by Django 4.2.3 on 2023-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='default_user_banner.jpg', upload_to='users_data/banners'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_user_image.jpg', upload_to='users_data/avatars'),
        ),
    ]
