# Generated by Django 4.2.3 on 2023-07-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_banner_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='default_banner.png', upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_avatar.png', upload_to='avatars'),
        ),
    ]
