# Generated by Django 4.2.3 on 2023-08-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_banner_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
